### ISSUE TITLE
tag can be without any ``

### ISSUE THREAD

**Issue by frolovdev** [frolovdev/anyspec#18]
tag can be without any `` 

https://github.com/Ajaxy/tinyspec#endpoint-tags

```
Admin:
    GET /users
```

**Comment by aimmlegate** [comment]
We have a problem with parsing/lexing endpoints definitions
In original implementation https://github.com/Ajaxy/tinyspec#endpoint-tags 
```
Admin endpoints:
    GET /articles (admin)?filter&sort&limit:i
        => {articles: Article[], totalCount: i}
```
tinyspec take a whole string at the top indentation level and use it as `tag`.

We cant do that right now, our lexer expects the same syntax rules in the whole file. 
Based on examples I wrote a lexer that creates `TokenKind.NAME` when it encounters:  
1. a sequence of characters until it sees <space> or other unexpected char
2. all string inside ascend characters ``
3. when it sees `/` character until <space>  (for URLs definitions)

Current implementation of endpoints parser can work with tags like that 

```
analytics_events:
  POST /endpoint RequestModel
    => ResponseModel
`;
```
and like that
```
`/analytics_events`:
  POST /endpoint RequestModel
    => ResponseModel
`;
```

So we have two problems:

1. Our current implementation parses incorrectly tags because I incorrectly assumed that grave accent marks are part of the tinyspec syntax.
```
`/analytics_events`: => { tag: /analytics_events }
```
but original implementation do than

```
`/analytics_events`: => { tag: `/analytics_events` }
```

2. Our current implementation cant parse cases like that at all

```
Admin endpoints:
    GET /articles (admin)?filter&sort&limit:i
        => {articles: Article[], totalCount: i}
```


I see only two options:
1. We stick with the current variant and enforce the rule that tags should be in `` or without spaces `AdminEndpoints`
2. We modify our lexer to parse TokenKind.NAME tokens differently based on indentation levels.

**Comment by frolovdev** [comment]
Put on pause, I have to talk with target main client :d

**Comment by frolovdev** [comment]
So as a result in our language we never will be support tags without ``
