### ISSUE TITLE
Model fields with "+", "-" should not ignore them

### ISSUE THREAD

**Issue by aimmlegate** [frolovdev/anyspec#98]
```
A # comment {
  {
  b,
  # comment
  b?,
  -b,
  -b?: i,
  -b?: i,
}
```

Right now for some reason, we skip `-`, `+` in fields name. Need to parse it

**Comment by frolovdev** [comment]
Do we really need to parse them?

First about `-`

Because `-` in field treats as `skip: true` property in node. Maybe it's much better to just handle this output in printer like that

```
if (skip) {
  return `-${field}`
}

```

About `+` sign,I ban this type of fields in lexer because it kind of weird thing to do. I don't know cases for now where it can be useful have `+` sign in your fields

**Comment by frolovdev** [comment]
Close due to clarification
